seed: 47
# training
window_len: 1
batch_size: 2
warmup: 100
lr: 0.001
adam_beta1: 0.9
adam_beta2: 0.98
max_updates: 5000
# eval
use_mean: False
# architecture
d_model: 512
d_latent: 2
num_layers: 4
lstm_layers: 3
state_len: 1
bottom_up: True
wandb_tag: lstm