seed: 47
# training
window_len: 4
batch_size: 128
warmup: 100
lr: 0.001
adam_beta1: 0.9
adam_beta2: 0.98
max_updates: 500
# eval
use_mean: False
# architecture
d_model: 512
num_layers: 4
state_len: 2
bottom_up: False
wandb_tag: baseline