seed: 47
# training
window_len: 3
batch_size: 64
warmup: 100
lr: 0.0005
adam_beta1: 0.9
adam_beta2: 0.98
max_updates: 500
# eval
use_mean: False
# architecture
d_model: 512
num_layers: 4
lstm_layers: 3
state_len: 1
bottom_up: True
wandb_tag: lstm